### ISSUE TITLE
trying to run it in the powerbi framework

### ISSUE THREAD

**Issue by Mxesli** [lmcarreiro/ui5ts#2]
i want to use this inside the powerbi framework and compiler but i wont compile at all.
1st : `error  TYPESCRIPT  C:/Work/PowerBI/test/node_modules/ui5ts/ui5-types/1.46/sap.d.ts : (110122,87) Cannot find name 'Promise'.
 error  TYPESCRIPT  C:/Work/PowerBI/test/node_modules/ui5ts/ui5-types/1.46/sap.d.ts : (110468,27) In ambient enum declarations member initializer must be constant expression.
 error  TYPESCRIPT  C:/Work/PowerBI/test/node_modules/ui5ts/ui5-types/1.46/sap.d.ts : (110472,30) In ambient enum declarations member initializer must be constant expression.
 error  TYPESCRIPT  C:/Work/PowerBI/test/node_modules/ui5ts/ui5-types/1.46/sap.d.ts : (111496,24) In ambient enum declarations member initializer must be constant expression.
 error  TYPESCRIPT  C:/Work/PowerBI/test/node_modules/ui5ts/ui5-types/1.46/sap.d.ts : (111500,25) In ambient enum declarations member initializer must be constant expression.
 error  TYPESCRIPT  C:/Work/PowerBI/test/node_modules/ui5ts/ui5-types/1.46/sap.d.ts : (111504,23) In ambient enum declarations member initializer must be constant expression.
 error  TYPESCRIPT  C:/Work/PowerBI/test/node_modules/ui5ts/ui5-types/1.46/sap.d.ts : (111508,26) In ambient enum declarations member initializer must be constant expression.
 error  TYPESCRIPT  C:/Work/PowerBI/test/node_modules/ui5ts/ui5-types/1.46/sap.d.ts : (111844,26) Class 'AnalyticalTable' incorrectly extends base class 'Table'.
  Types of property 'addSelectionInterval' are incompatible.
    Type '(iFromIndex: number, iToIndex: number) => AnalyticalTable' is not assignable to type '(iIndexFrom: number, iIndexTo: number) => Table'.
      Type 'AnalyticalTable' is not assignable to type 'Table'.
        Types of property 'setSelectionBehavior' are incompatible.
          Type '(sBehavior: string) => Table' is not assignable to type '(sSelectionBehavior: SelectionBehavior) => Table'.
            Types of parameters 'sBehavior' and 'sSelectionBehavior' are incompatible.
              Type 'SelectionBehavior' is not assignable to type 'string'.
 error  TYPESCRIPT  C:/Work/PowerBI/test/node_modules/ui5ts/ui5-types/1.46/sap.d.ts : (112997,25) In ambient enum declarations member initializer must be constant expression.
 error  TYPESCRIPT  C:/Work/PowerBI/test/node_modules/ui5ts/ui5-types/1.46/sap.d.ts : (113001,37) In ambient enum declarations member initializer must be constant expression.
 error  TYPESCRIPT  C:/Work/PowerBI/test/node_modules/ui5ts/ui5-types/1.46/sap.d.ts : (113005,28) In ambient enum declarations member initializer must be constant expression.
 error  TYPESCRIPT  C:/Work/PowerBI/test/node_modules/ui5ts/ui5-types/1.46/sap.d.ts : (113009,26) In ambient enum declarations member initializer must be constant expression.
 error  TYPESCRIPT  C:/Work/PowerBI/test/node_modules/ui5ts/ui5-types/1.46/sap.d.ts : (113013,37) In ambient enum declarations member initializer must be constant expression.
 error  TYPESCRIPT  C:/Work/PowerBI/test/node_modules/ui5ts/ui5-types/1.46/sap.d.ts : (113017,27) In ambient enum declarations member initializer must be constant expression.
 error  TYPESCRIPT  C:/Work/PowerBI/test/node_modules/ui5ts/ui5-types/1.46/sap.d.ts : (113021,30) In ambient enum declarations member initializer must be constant expression.
 error  TYPESCRIPT  C:/Work/PowerBI/test/node_modules/ui5ts/ui5-types/1.46/sap.d.ts : (113033,29) In ambient enum declarations member initializer must be constant expression.
 error  TYPESCRIPT  C:/Work/PowerBI/test/node_modules/ui5ts/ui5-types/1.46/sap.d.ts : (113037,29) In ambient enum declarations member initializer must be constant expression.` <-- this goes on for ever

2nd: in the sap.d.ts i am getting an error : The name "IterableIterator" wanst found

its here a way to fix that issue or is it almost impossible to run ui5 in typescript and the powerbi custom visual framework?

**Comment by lmcarreiro** [comment]
> 2nd: in the sap.d.ts i am getting an error : The name "IterableIterator" wanst found

I'm getting this error too.

I don't know the powerbi framework, do you have a tsconfig.json file in it? Could you share its content?

**Comment by Mxesli** [comment]
@lmcarreiro I removed the framework from my power bi visual and i looking for a framework with an wrapper for power bi, but thx <3

**Comment by lmcarreiro** [comment]
Closing... This repository is being archived. Now the ui5ts package is maintained at https://github.com/neoprincie/ui5ts
