### ISSUE TITLE
Autogenerated code is not handled

### ISSUE THREAD

**Issue by rg1** [lmcarreiro/ui5ts#4]
First let me say thank you for your module. It allows me to use types in many more places than I could without.

I'd like to point out, though, that the autogenerated methods for anything in metadata (properties, etc) are not handled and need to be duplicated in your own code to be accessible without type errors. While I don't think it can be done with the (unmodified) typescript compiler, I'd like to see it mentioned in the README file. If you have any idea how to handle metadata better or even automatically, I'd love to know.

**Comment by lmcarreiro** [comment]
Closing... This repository is being archived. Now the ui5ts package is maintained at https://github.com/neoprincie/ui5ts
